@host = http://localhost:3000



#PING TEST
GET {{host}}/
Content-Type: application/json

###

#HEALTH CHECK
GET {{host}}/health
Content-Type: application/json


###

#LOGIN USER
POST {{host}}/api/auth/registration
Content-Type: application/json

{
  "fullName": "{{fullname}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "userType": "{{userType}}"
}

###


#GET USER
GET {{host}}/api/users/e2fccfd2-e4db-40f9-90a4-f07ee55670ab
Content-Type: application/json
